apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-bloom
  namespace: ourbox-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-bloom
  template:
    metadata:
      labels:
        app: todo-bloom
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: static
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: static
          hostPath:
            path: /var/lib/ourbox/todo-bloom
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: todo-bloom
  namespace: ourbox-system
spec:
  selector:
    app: todo-bloom
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
