apiVersion: apps/v1
kind: Deployment
metadata:
  name: dufs
  namespace: ourbox-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dufs
  template:
    metadata:
      labels:
        app: dufs
    spec:
      enableServiceLinks: false
      containers:
        - name: dufs
          image: sigoden/dufs:v0.42.0
          imagePullPolicy: Never
          args: ["/data", "-A"]
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: share
              mountPath: /data
      volumes:
        - name: share
          hostPath:
            path: /var/lib/ourbox/share
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: dufs
  namespace: ourbox-system
spec:
  selector:
    app: dufs
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: 5000
