apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatnotes
  namespace: ourbox-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flatnotes
  template:
    metadata:
      labels:
        app: flatnotes
    spec:
      enableServiceLinks: false
      containers:
        - name: flatnotes
          image: dullage/flatnotes:v5.0.0
          imagePullPolicy: Never
          env:
            - name: FLATNOTES_AUTH_TYPE
              value: "none"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: notes
              mountPath: /data
      volumes:
        - name: notes
          hostPath:
            path: /var/lib/ourbox/flatnotes
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: flatnotes
  namespace: ourbox-system
spec:
  selector:
    app: flatnotes
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
